In [1]:
import numpy as np

In [71]:
def base_convert(number, base, length):
    list_q = [0] * length
    number_q = np.base_repr(number, base=q)
    for idx, i in enumerate(number_q):
        list_q[length - len(number_q) + idx] = int(i)
    return np.array(list_q)

def inner_product(x, y, base):
    return np.mod(np.sum(x * y), q)

In [93]:
q = 4
fixed_chars = np.array([1,1,0,0])
ref_index = np.array([1,2,0,0])
n = len(ref_index)

nf_chars = np.where(fixed_chars == 0)[0]
nf_count = len(nf_chars)

power_matrix = np.zeros((1 + nf_count*(q-1), q**nf_count), np.int32)

for i in range(nf_count):
    for j in range(q-1):
        p_index = [0] * n
        p_index[nf_chars[i]] = j + 1
        
        for s in range(q**nf_count):
            s_index_short = base_convert(s, q, nf_count)
            s_index = ref_index.copy()
            s_index[nf_chars] = s_index_short
            
            power_matrix[(q-1)*i + j + 1, s] = inner_product(s_index, p_index, q)
            
print(power_matrix)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 1 1 2 2 2 2 3 3 3 3]
 [0 0 0 0 2 2 2 2 0 0 0 0 2 2 2 2]
 [0 0 0 0 3 3 3 3 2 2 2 2 1 1 1 1]
 [0 1 2 3 0 1 2 3 0 1 2 3 0 1 2 3]
 [0 2 0 2 0 2 0 2 0 2 0 2 0 2 0 2]
 [0 3 2 1 0 3 2 1 0 3 2 1 0 3 2 1]]


In [94]:
import pandas as pd

rows = [''.join(str(e) for e in [0] * n)]

for i in range(nf_count):
    for j in range(q-1):
        p_index = [0] * n
        p_index[nf_chars[i]] = j + 1
        rows.append(''.join(str(e) for e in p_index))
    
cols = []
for s in range(q**nf_count):
    s_index_short = base_convert(s, q, nf_count)
    s_index = ref_index.copy()
    s_index[nf_chars] = s_index_short
    cols.append(''.join(str(e) for e in s_index))

df = pd.DataFrame(power_matrix, columns=cols, index=rows)
print(df)

      1200  1201  1202  1203  1210  1211  1212  1213  1220  1221  1222  1223  \
0000     0     0     0     0     0     0     0     0     0     0     0     0   
0010     0     0     0     0     1     1     1     1     2     2     2     2   
0020     0     0     0     0     2     2     2     2     0     0     0     0   
0030     0     0     0     0     3     3     3     3     2     2     2     2   
0001     0     1     2     3     0     1     2     3     0     1     2     3   
0002     0     2     0     2     0     2     0     2     0     2     0     2   
0003     0     3     2     1     0     3     2     1     0     3     2     1   

      1230  1231  1232  1233  
0000     0     0     0     0  
0010     3     3     3     3  
0020     2     2     2     2  
0030     1     1     1     1  
0001     0     1     2     3  
0002     0     2     0     2  
0003     0     3     2     1  
